#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 25 12:58:33 2020

@author: giuliataurino
"""

#import packages
from pprint import pprint
import requests
import json
import urllib3
import praw
import pandas as pd
import datetime as dt


#Getting Reddit and subreddit instances
reddit = praw.Reddit(client_id='PERSONAL_USE_SCRIPT_14_CHARS', \
                     client_secret='SECRET_KEY_27_CHARS ', \
                     user_agent='YOUR_APP_NAME', \
                     username='YOUR_REDDIT_USER_NAME', \
                     password='YOUR_REDDIT_LOGIN_PASSWORD')

subreddit = reddit.subreddit('westworld')

#Accessing the thread
top_subreddit = subreddit.top()
top_subreddit = subreddit.top(limit=1000)

#Parsing and downloading the data  
for submission in subreddit.top(limit=1):
    print(submission.title, submission.id)
  
topics_dict = { "title":[], \
                "score":[], \
                "id":[], "url":[], \
                "comms_num": [], \
                "created": [], \
                "body":[]}

#scraping data
for submission in top_subreddit:
    topics_dict["title"].append(submission.title)
    topics_dict["score"].append(submission.score)
    topics_dict["id"].append(submission.id)
    topics_dict["url"].append(submission.url)
    topics_dict["comms_num"].append(submission.num_comments)
    topics_dict["created"].append(submission.created)
    topics_dict["body"].append(submission.selftext)

#Python dictionaries
topics_data = pd.DataFrame(topics_dict)

#Fixing the date column
def get_date(created):
    return dt.datetime.fromtimestamp(created)
_timestamp = topics_data["created"].apply(get_date)
topics_data = topics_data.assign(timestamp = _timestamp)

#Exporting a CSV
topics_data.to_csv('FILENAME.csv', index=False) 



